# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to ~/.config/fish/completions/mqtt-rpc-client.fish
# 2) Ensure a binary named mqtt-rpc-client is in your PATH
# See also: https://fishshell.com/docs/current/completions.html#where-to-put-completions


# Parse current commandline:
# - _shtab_wb_common_cmdpath=(sub)command path seen so far
# - _shtab_wb_common_npos=number of positional arguments given after it
# - options are skipped based on _shtab_wb_common_opts_with_value & _shtab_wb_common_commands lists
function _shtab_wb_common_scan
  set -g _shtab_wb_common_cmdpath ''
  set -g _shtab_wb_common_npos 0
  set -l tokens (commandline -opc)
  set -e tokens[1]
  set -l expect_value 0
  for t in $tokens
    if test $expect_value -eq 1
      set expect_value 0
      continue
    end
    switch "$t"
      case '--*=*'
        continue
      case '-*'
        if contains -- $t $_shtab_wb_common_opts_with_value
          set expect_value 1
        end
        continue
      case '*'
        if test $_shtab_wb_common_npos -eq 0
          set -l candidate $t
          if test -n "$_shtab_wb_common_cmdpath"
            set candidate "$_shtab_wb_common_cmdpath $t"
          end
          if contains -- $candidate $_shtab_wb_common_commands
            set -g _shtab_wb_common_cmdpath $candidate
            continue
          end
        end
        set -g _shtab_wb_common_npos (math $_shtab_wb_common_npos + 1)
    end
  end
end

# Condition helper: true if the current (sub)command path equals the given one.
function _shtab_wb_common_using
  _shtab_wb_common_scan
  test "$_shtab_wb_common_cmdpath" = "$argv"
end

set -g _shtab_wb_common_commands 
set -g _shtab_wb_common_opts_with_value --args --broker --driver --method --service --timeout -a -b -d -m -s -t

complete -c mqtt-rpc-client -e
complete -c mqtt-rpc-client -f

complete -c mqtt-rpc-client -n _shtab_wb_common_using -s h -l help -d 'show this help message and exit'
complete -c mqtt-rpc-client -n _shtab_wb_common_using -s b -l broker -x -d 'MQTT broker url (default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c mqtt-rpc-client -n _shtab_wb_common_using -s d -l driver -x -d 'Driver name (default: None)'
complete -c mqtt-rpc-client -n _shtab_wb_common_using -s s -l service -x -d 'Service name (default: None)'
complete -c mqtt-rpc-client -n _shtab_wb_common_using -s m -l method -x -d 'Method name (default: None)'
complete -c mqtt-rpc-client -n _shtab_wb_common_using -s a -l args -x -d 'Method arguments (default: {})'
complete -c mqtt-rpc-client -n _shtab_wb_common_using -s t -l timeout -x -d 'Timeout in seconds (default: 10)'

